springdoc.swagger-ui.oauth.use-pkce-with-authorization-code-grant=true
springdoc.swagger-ui.oauth.client-secret=irrelevantBecauseWeReConnectingToAPublicClient

spring.jackson.default-property-inclusion=NON_ABSENT

# Enable response compression
server.compression.enabled=true
# Minimum response where compression will kick in
server.compression.min-response-size=4096
# Mime types that should be compressed
server.compression.mime-types=text/html, text/xml, text/plain, text/css, text/javascript, application/javascript, application/json

# Actuator config
management.endpoints.web.exposure.include=health,info,prometheus

org.marmotgraph.api.root=/api
springdoc.api-docs.path=${org.marmotgraph.api.root}/docs

org.marmotgraph.tenant=default